"""
FinShield - Debt Simulation Engine

Simulates loan repayment schedules for synthetic SMEs.

The engine produces:
    - Loan principal
    - Interest rate
    - Tenure
    - EMI
    - Interest payment
    - Principal payment
    - Remaining balance

The resulting schedule represents a known future financial
obligation that can later be supplied to the forecasting model.
"""

import random

from config import RANDOM_SEED


# ============================================================
# RANDOM GENERATOR
# ============================================================

rng = random.Random(RANDOM_SEED + 400)


# ============================================================
# LOAN PARAMETERS
# ============================================================

LOAN_PROFILES = {

    "retail": {
        "interest_rate": (0.09, 0.16),
        "tenure_months": (24, 60),
    },

    "wholesale": {
        "interest_rate": (0.09, 0.15),
        "tenure_months": (24, 60),
    },

    "manufacturing": {
        "interest_rate": (0.08, 0.14),
        "tenure_months": (36, 84),
    },

    "food_hospitality": {
        "interest_rate": (0.09, 0.16),
        "tenure_months": (24, 60),
    },

    "professional_services": {
        "interest_rate": (0.09, 0.15),
        "tenure_months": (24, 60),
    },
}


# ============================================================
# HELPERS
# ============================================================

def uniform(low, high):
    """Generate a random value between low and high."""
    return rng.uniform(low, high)


def calculate_emi(
    principal,
    annual_interest_rate,
    tenure_months,
):
    """
    Calculate monthly EMI using the standard amortization formula.

    EMI = P * r * (1+r)^n / ((1+r)^n - 1)

    where:
        P = principal
        r = monthly interest rate
        n = number of months
    """

    if principal <= 0:
        return 0.0

    monthly_rate = (
        annual_interest_rate / 12
    )

    if monthly_rate == 0:
        return (
            principal / tenure_months
        )

    factor = (
        (1 + monthly_rate)
        ** tenure_months
    )

    emi = (
        principal
        * monthly_rate
        * factor
        / (factor - 1)
    )

    return emi


# ============================================================
# LOAN GENERATION
# ============================================================

def generate_loan(company):
    """
    Generate one loan for the company.

    The opening principal is based on the company's
    existing debt balance generated by company_generator.py.
    """

    sector = company["sector"]

    profile = LOAN_PROFILES[sector]

    principal = max(
        company["debt_balance"],
        0.0
    )

    annual_interest_rate = uniform(
        profile["interest_rate"][0],
        profile["interest_rate"][1],
    )

    tenure_months = rng.randint(
        profile["tenure_months"][0],
        profile["tenure_months"][1],
    )

    emi = calculate_emi(
        principal=principal,
        annual_interest_rate=annual_interest_rate,
        tenure_months=tenure_months,
    )

    return {
        "loan_id": (
            f"{company['company_id']}_LOAN_001"
        ),

        "company_id": company[
            "company_id"
        ],

        "principal": round(
            principal,
            2
        ),

        "annual_interest_rate": round(
            annual_interest_rate,
            4
        ),

        "tenure_months": tenure_months,

        "emi": round(
            emi,
            2
        ),
    }


# ============================================================
# MONTHLY LOAN PAYMENT
# ============================================================

def calculate_monthly_payment(
    beginning_balance,
    annual_interest_rate,
    scheduled_emi,
):
    """
    Calculate interest, principal and total payment
    for one month.
    """

    if beginning_balance <= 0:
        return {
            "interest_payment": 0.0,
            "principal_payment": 0.0,
            "total_payment": 0.0,
            "ending_balance": 0.0,
        }

    monthly_rate = (
        annual_interest_rate / 12
    )

    interest_payment = (
        beginning_balance
        * monthly_rate
    )

    scheduled_principal = (
        scheduled_emi
        - interest_payment
    )

    # Protect against unusual parameter combinations.
    scheduled_principal = max(
        scheduled_principal,
        0.0
    )

    principal_payment = min(
        scheduled_principal,
        beginning_balance
    )

    total_payment = (
        interest_payment
        + principal_payment
    )

    ending_balance = max(
        beginning_balance
        - principal_payment,
        0.0
    )

    return {
        "interest_payment": round(
            interest_payment,
            2
        ),

        "principal_payment": round(
            principal_payment,
            2
        ),

        "total_payment": round(
            total_payment,
            2
        ),

        "ending_balance": round(
            ending_balance,
            2
        ),
    }


# ============================================================
# DEBT SCHEDULE
# ============================================================

def generate_debt_schedule(
    company,
    months=36,
    start_date="2023-01-01",
):
    """
    Generate a month-by-month debt schedule.

    The schedule contains future known obligations.

    Parameters
    ----------
    company : dict
        Static company profile.

    months : int
        Number of months to simulate.

    start_date : str
        Simulation start date.

    Returns
    -------
    tuple
        loan information and monthly schedule.
    """

    from revenue_engine import get_date

    loan = generate_loan(company)

    beginning_balance = loan[
        "principal"
    ]

    schedule = []

    for month_index in range(months):

        payment = calculate_monthly_payment(
            beginning_balance=beginning_balance,
            annual_interest_rate=loan[
                "annual_interest_rate"
            ],
            scheduled_emi=loan["emi"],
        )

        schedule.append(
            {
                "company_id": company[
                    "company_id"
                ],

                "loan_id": loan[
                    "loan_id"
                ],

                "month_index": month_index,

                "month": get_date(
                    month_index,
                    start_date
                ),

                "beginning_debt_balance":
                    round(
                        beginning_balance,
                        2
                    ),

                "scheduled_emi":
                    payment[
                        "total_payment"
                    ],

                "interest_payment":
                    payment[
                        "interest_payment"
                    ],

                "principal_payment":
                    payment[
                        "principal_payment"
                    ],

                "ending_debt_balance":
                    payment[
                        "ending_balance"
                    ],

                # This flag is useful for TFT later.
                "payment_due": (
                    payment[
                        "total_payment"
                    ] > 0
                ),
            }
        )

        beginning_balance = payment[
            "ending_balance"
        ]

    return loan, schedule


# ============================================================
# SUMMARY
# ============================================================

def print_debt_summary(
    loan,
    schedule,
):
    """Print debt schedule summary."""

    print("\n" + "=" * 70)
    print("FINSHIELD DEBT ENGINE")
    print("=" * 70)

    print(
        f"Loan ID: "
        f"{loan['loan_id']}"
    )

    print(
        f"Principal: "
        f"₹{loan['principal']:,.0f}"
    )

    print(
        f"Annual interest rate: "
        f"{loan['annual_interest_rate'] * 100:.2f}%"
    )

    print(
        f"Tenure: "
        f"{loan['tenure_months']} months"
    )

    print(
        f"Scheduled EMI: "
        f"₹{loan['emi']:,.0f}"
    )

    print(
        f"\nMonths simulated: "
        f"{len(schedule)}"
    )

    total_interest = sum(
        row["interest_payment"]
        for row in schedule
    )

    total_principal = sum(
        row["principal_payment"]
        for row in schedule
    )

    total_payments = sum(
        row["scheduled_emi"]
        for row in schedule
    )

    print(
        f"Interest paid in simulation: "
        f"₹{total_interest:,.0f}"
    )

    print(
        f"Principal paid in simulation: "
        f"₹{total_principal:,.0f}"
    )

    print(
        f"Total debt payments: "
        f"₹{total_payments:,.0f}"
    )

    print("\nFirst 6 months:")

    for row in schedule[:6]:

        print(
            f"  {row['month']} | "
            f"EMI ₹{row['scheduled_emi']:,.0f} | "
            f"Interest ₹{row['interest_payment']:,.0f} | "
            f"Principal ₹{row['principal_payment']:,.0f} | "
            f"Remaining ₹{row['ending_debt_balance']:,.0f}"
        )

    print("\nLast simulated month:")

    last = schedule[-1]

    print(
        f"  {last['month']} | "
        f"Remaining debt "
        f"₹{last['ending_debt_balance']:,.0f}"
    )

    print("=" * 70)


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    from company_generator import (
        generate_companies,
    )

    # --------------------------------------------------------
    # Generate one company
    # --------------------------------------------------------

    companies = generate_companies(
        total_companies=1
    )

    company = companies[0]

    # --------------------------------------------------------
    # Generate debt schedule
    # --------------------------------------------------------

    loan, schedule = (
        generate_debt_schedule(
            company=company,
            months=36,
        )
    )

    print(
        f"\nTesting company: "
        f"{company['company_id']}"
    )

    print(
        f"Sector: "
        f"{company['sector']}"
    )

    print(
        f"Company size: "
        f"{company['company_size']}"
    )

    print_debt_summary(
        loan,
        schedule,
    )